"""empty message

Revision ID: 2df4994bea3f
Revises: 26f66be6bef4
Create Date: 2024-11-10 21:14:07.029927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2df4994bea3f'
down_revision = '26f66be6bef4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('demand')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('demand', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
